# Generated by Django 4.1.3 on 2022-12-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_terror', '0003_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, null='True', upload_to='posts'),
            preserve_default='True',
        ),
    ]
